### ISSUE TITLE
devices.json File Not Present

### ISSUE THREAD

**Issue by jmwright** [Wakoma/nimble#104]
I am getting the following error on master when trying to run the tests locally.
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwright/mambaforge/envs/nimble/lib/python3.11/site-packages/nimble_build_system/orchestration/../../devices.json'
```

I see that the devices.json file that is present in the root of this repository is not listed as a data file in setup.py.

**Comment by jmwright** [comment]
Apparently the `devices.json` file needs to be in `site-packages` to get the tests to run.

**Comment by julianstirling** [comment]
Nimble is only pip installed to make minimise path issues when calling python. It needs to bin installed with `-e` option to work. This should remove the need for site-packages
