### ISSUE TITLE
cadquery scripts should be executed using cq-cli or cqgi 

### ISSUE THREAD

**Issue by drayde** [Wakoma/nimble#15]
As discussed here https://github.com/Wakoma/nimble/pull/14#issuecomment-1939636739
cadquery scripts should only be executed using cq-cli or cqgi https://cadquery.readthedocs.io/en/latest/cqgi.html

This currently affects only this code
https://github.com/Wakoma/nimble/blob/a1540a2604a55a963363d3a79703284351d099d3/doc_generator/server/nimble_server.py#L117-L129
but we probably will introduce more code like this in the future.

When this is done, we can get rid of the if statement for imports in cadquery scripts like this one:
https://github.com/Wakoma/nimble/blob/791da1e2ba7c7905b309d9f430f046b28147e335/doc_generator/mechanical/components/cadquery/rack_leg.py#L4-L7

**Comment by jmwright** [comment]
Resolved by #16
