### ISSUE TITLE
Ziptie Shelf Prototype

### ISSUE THREAD

**Issue by ericnitschke** [Wakoma/nimble#17]
New design for attaching any* hardware to a shelf.

STL Link: https://github.com/Wakoma/nimble/blob/master/gen/2024%20designs/parametric%20(primary)/shelf_6in_2u_anker-atom3slim.stl

**Comment by ericnitschke** [comment]
design by @drayde 
test print:

![Image](https://github.com/Wakoma/nimble/assets/36915805/f7df2b5f-eb33-4a5b-9628-bd7be933329f)
![Image](https://github.com/Wakoma/nimble/assets/36915805/14fb0d6f-8aa3-47d0-b9ef-c5f3237a07e1)

**Comment by drayde** [comment]
@ericnitschke can we mark this as done?

**Comment by David-ksturnpike** [comment]
could this be merged into issue number #24?  or would this be a separate issue?

**Comment by drayde** [comment]
If support of velcro is the only issue, i'd close this one. If there are other issues to be addressed, I'd handle those here

**Comment by julianstirling** [comment]
I agree. I think we close this a zip-ties are already working and implemented. We can keep #24 open as this reminds us that we should also support Velcro as and when we have time.
