### ISSUE TITLE
Open Source Hardware - some Info is missing

### ISSUE THREAD

**Issue by timmwille** [Wakoma/nimble#2]
Hi Guys do you need some suggestions regarding the Openess of this project? CERN OHL 2.0 (S or W might fit best) or other License might be best, currently I could not find a License file/note.

Where would I find the Source files (so far the stl is mesh not CAD based format)?

I'm working within the context of Open Source Ecology and the Open Culture agency within South Sudan, Uganda and other regions, might be very interesting to collaborate.

**Comment by timmwille** [comment]
from the software side all seems clear: https://github.com/Wakoma/Lokal

thanks for the great work, I would love to test it

**Comment by timmwille** [comment]
I hope my PR helps to make it easy, in general the source files can be in the tinkercad though on my end even activating al skripts it looks like this:

![grafik](https://user-images.githubusercontent.com/8081055/205046630-e9aef536-f108-4493-be3b-9d0cbd891529.png)

**Comment by ericnitschke** [comment]
thanks very much @timmwille and @moedn.  Would love to jump on a call with your team to discuss license options, Lokal install, etc. On our main website we do have the nimble license as CC-BY-SA 4.0, but we're open to other options. 

Looks like one must be logged into Tinkercad to access the source files, which isn't ideal.  Glad to move/convert/share them as necessary.

New Lokal release coming out very soon, along with some much needed documentation.  

Looking forward to connecting soon.

**Comment by moedn** [comment]
Cool! I'm pretty flexible next week. @ericnitschke please feel free to pick a slot that suits you :) Not sure if @timmwille will be able to join since he's quite busy these days, but I'll be happy to bring in his input :)

**Comment by hoijui** [comment]
All of this has been solved in the hackathon on march 3. and 4. 2023. The project is now primarily using `CERN-OHL-S-2.0`. :-)

(Issue can be closed)

**Comment by ericnitschke** [comment]
Thank you everyone for your inputs on this at the hackathon!  Case closed.
