### ISSUE TITLE
STLs in main Repository

### ISSUE THREAD

**Issue by julianstirling** [Wakoma/nimble#20]
I have just notices we are committing the STLs to the repo. STL files can get large and as Git clone pulls the entire history this very quickly turns into a project that can only be contributed to by people with good internet connection. Something we cannot ensure Nimbe contributors will have. OpenFlexure had this issue, it made it almost impossible to work on the repository in Africa.

Is the idea to commit all the legacy nimble files as STLs then remove them as we make parametric ones? Or are these the new generated ones? f they are they have no business being in a repo and should be purged from the history with BFG and we should be using CI to generate them

Can we have a meeting to discus the repo?

**Comment by ericnitschke** [comment]
Thanks, @julianstirling. Solid point.  I just put them (old ones and new) up [here](https://github.com/Wakoma/nimble/tree/master/gen) for the sake of openness.  

We could perhaps keep the archive and parametric files under development in Nextcloud, and just add the most recent versions on GH? (or offload to Printables or Appropedia?) Glad to discuss on the next call. 

It might also make sense to build a compressed offline-first archive of all designs and documentation in a few months. (i.e. https://github.com/openzim/zim-requests/issues/793).

**Comment by ericnitschke** [comment]
consensus that STLs should be removed from repo and added to static site for now

**Comment by drayde** [comment]
removed the new STL files, left in the 2023 versions in for now (to be deleted when we have the new workflow ready).
For new static site, see #21
