### ISSUE TITLE
Create mock-up of final UI

### ISSUE THREAD

**Issue by julianstirling** [Wakoma/nimble#43]

**Comment by jmwright** [comment]
As a companion to the server backend in #45 I created a simple web front end for testing.

[README](https://github.com/Wakoma/nimble/blob/smart_doc/doc_generator/server/README.md)

[HTML](https://github.com/Wakoma/nimble/blob/smart_doc/doc_generator/server/test_page.html)

[Javascript](https://github.com/Wakoma/nimble/blob/smart_doc/doc_generator/server/static/js/index.js#L6)

**Comment by ericnitschke** [comment]
A few older mock-ups by Wakoma team. (front) end product will likely be quite different. 

![image](https://github.com/Wakoma/nimble/assets/36915805/f34e8e68-90c9-4180-be66-8d8f207dd393)

![image](https://github.com/Wakoma/nimble/assets/36915805/4d94e335-f361-45e2-84d9-72ad755f1873)

![image](https://github.com/Wakoma/nimble/assets/36915805/92715af2-abb5-4081-ab4c-e9ad7a3d6079)

![image](https://github.com/Wakoma/nimble/assets/36915805/94e9dbdd-4607-46f6-8cff-b2a77eb11a4c)

**Comment by julianstirling** [comment]
These are nice. We also have the demo server which was in plain JS.

![Image](https://github.com/Wakoma/nimble/assets/12807051/5af77193-04ef-4647-a9d3-ae791f410d85)

---

I think the best path forward is to move the current demo server into a more extensible framework (VueJS 3) and then have a bit of a think about it want to pull elements of this @ericnitschke mockups into the the server.

The issue I see with doing this is we are going to need the images and description text to be added to the database for each item. This isn't insurmountable, but may be a fair amount of work.
