### ISSUE TITLE
Fastener Models in Assemblies

### ISSUE THREAD

**Issue by jmwright** [Wakoma/nimble#71]
We have started to discuss adding fasteners to assemblies, specifically metric screws to install components into shelves, and screws to mount the shelves into the rack. It looks like there is only one complete generator library at this time, and that is [cq_warehouse](https://cq-warehouse.readthedocs.io/en/latest/fastener.html). It does other things besides fasteners, but I doubt we need any of the other parts it generates.

The alternative is to generate our own fasteners, but there is a surprising amount of nuance in fasteners that can make them tedious to create.

**Comment by julianstirling** [comment]
My vote is to use cq_warehouse. Better to use a package than reinvent the wheel.

**Comment by jmwright** [comment]
The cq_warehouse dependency has been added in draft PR #75

**Comment by jmwright** [comment]
The assemblies that have been done so far have fasteners. Screws are created using cq_warehouse, and I created zip tie fasteners as well.
