### ISSUE TITLE
Plan data structure and information flow

### ISSUE THREAD

**Issue by julianstirling** [Wakoma/nimble#78]
We need to make sure that the correct data is available to each step of generating the hardware and instructions. A first approximation is that the following data is needed for the three main steps:

![Image](https://github.com/Wakoma/nimble/assets/12807051/26288786-2190-443e-97f7-deeeacea2773)

I think the easiest way to do this is some sort of heptarchical object-based structure. Very simplistically this will look somewhat like:

![Image](https://github.com/Wakoma/nimble/assets/12807051/8e02e958-2867-489c-8f27-b581930ea6d6)

This way the orchestration can:

1. Receive list of networking hardware and rack parameters
2. Pass parameters into full assembly object
    1. Orchestration adds networking component to object
    2. Assembly object then creates shelf object based on this (needs access to database to know what shelf type and other information.)
3. Get ExSource from assembly object to get full list of parts and renders that need to be generated (object will need to query the other objects it contains)
4. Run ExSource
5. Get textual instructions from assembly object (object will need to query the other objects it contains)
6. Run GitBuilding

## Shelf classes

- We will need a base high level shelf class that contains all the basic structure.
- We will then need a generic shelf class that creates the shelf (and stores other info) for any networking hardware that doesn't have specific shelves
- We will need child classes for the very specific shelves for certain components.

**Comment by jmwright** [comment]
I don't think anything in the data flow precludes this, but it will probably be easier to make the shelves into sub-assemblies along with their components, screws, etc, and then have the entire rack be built of shelf-component sub-assemblies along with the odd bits that are left over (top and bottom plates, rails, screws to fasten sub-assemblies to rails, etc). This could imply a matching hierarchy in the data.

**Comment by julianstirling** [comment]
I'm closing this as we have have a plan. I'm sure the plan will be updated as we find the issues.
