### ISSUE TITLE
HDD 3.5" Mounting Hole Spacing

### ISSUE THREAD

**Issue by jmwright** [Wakoma/nimble#97]
@ericnitschke Have you printed one of the HDD 3.5" shelves to do a test fit? It looks like the hole spacing may be wrong on the shelf based on [this document](https://support.wdc.com/images/kb/2579-771970-A03.pdf) from Western Digital.

**Comment by ericnitschke** [comment]
Just the old/original version of the shelf, which works fine. It only uses two screws but holds the drive well. Pics [1](https://wakoma.co/wp-content/uploads/2024/10/hdd2-scaled.jpeg) [2](https://wakoma.co/wp-content/uploads/2024/10/hdd1-scaled.jpeg) I don't think we have a parametric design for this one.

**Comment by jmwright** [comment]
Thanks @ericnitschke
